name: Laravel Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}

          script: |
            cd /var/www/html/laravel

            git pull origin main

            composer install --no-interaction --prefer-dist --optimize-autoloader

            php artisan migrate --force

            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            sudo systemctl restart apache2